ner_labels: 
  - STRAIN
  - METABOLITE
  - SPECIES
  - ISOLATE
  - COMPOUND
  - MEDIUM
  - ORGANISM
  - PHENOTYPE
  - MORPHOLOGY
  - PROTEIN
  - EFFECT
  - DISEASE
  - GENUS
model_sets:
  - train
  - dev
  - test
epochs: 10
input_file: label/project-4-at-2023-12-28-19-03-703340b5.json
cutoff_prediction: 0.50
cuda_devices: [0,1,2,3]
test_size: 0.35
re_labels:
- STRAIN-ISOLATE:INHABITS
- STRAIN-METABOLITE:PRODUCES
- STRAIN-MEDIUM:GROWS_ON
- STRAIN-PHENOTYPE:PRESENTS
- STRAIN-PROTEIN:PRODUCES
- STRAIN-ORGANISM:INHABITS
- STRAIN-MORPHOLOGY:FORMS
- STRAIN-COMPOUND:RESISTS
- STRAIN-METABOLITE:RESISTS
- STRAIN-EFFECT:PROMOTES
- STRAIN-ORGANISM:INFECTS
- COMPOUND-STRAIN:INHIBITS
- STRAIN-EFFECT:PRESENTS
- STRAIN-METABOLITE:DEGRADES
- STRAIN-DISEASE:ASSOCIATED_WITH
- STRAIN-COMPOUND:DEGRADES
- METABOLITE-STRAIN:INHIBITS
- STRAIN-ORGANISM:SYMBIONT_OF
- STRAIN-EFFECT:ASSOCIATED_WITH
- STRAIN-SPECIES:INHIBITS
- STRAIN-COMPOUND:PRODUCES
