ner_labels: 
  - STRAIN
  - METABOLITE
  - SPECIES
  - ISOLATE
  - COMPOUND
  - MEDIUM
  - ORGANISM
  - PHENOTYPE
  - MORPHOLOGY
  - PROTEIN
  - EFFECT
  - DISEASE
rel_labels:
- STRAIN-ISOLATE:INHABITS
- STRAIN-METABOLITE:PRODUCES
- STRAIN-MEDIUM:GROWS_ON
- STRAIN-PHENOTYPE:PRESENTS
- STRAIN-PROTEIN:PRODUCES
- STRAIN-ORGANISM:INHABITS
- STRAIN-MORPHOLOGY:FORMS
- STRAIN-COMPOUND:RESISTS
- STRAIN-METABOLITE:RESISTS
- STRAIN-EFFECT:PROMOTES
- STRAIN-ORGANISM:INFECTS
- COMPOUND-STRAIN:INHIBITS
- STRAIN-EFFECT:PRESENTS
- STRAIN-METABOLITE:DEGRADES
- STRAIN-DISEASE:ASSOCIATED_WITH
- STRAIN-COMPOUND:DEGRADES
- METABOLITE-STRAIN:INHIBITS
- STRAIN-ORGANISM:SYMBIONT_OF
- STRAIN-EFFECT:ASSOCIATED_WITH
- STRAIN-SPECIES:INHIBITS
- STRAIN-COMPOUND:PRODUCES
model_sets:
  - train
  - dev
  - test
ner_epochs: 13
rel_epochs: 15
input_file: label/project-4-at-2024-04-09-13-48-f86e832f.json
cutoff_prediction: 0.50
cuda_devices: [0]
ner_test: 0.35
rel_test: 0.45
dataset : "1000"
model: "large"
seed: 42
max_assemblies: 500
min_samples: 3
xgboost_device: 1
word_size_limit: 3
