ner_labels:
  - STRAIN
  - SPECIES
  - ISOLATE
  - COMPOUND
  - MEDIUM
  - ORGANISM
  - PHENOTYPE
  - PROTEIN
  - EFFECT
  - DISEASE
rel_labels:
  - STRAIN-ISOLATE:INHABITS
  - STRAIN-MEDIUM:GROWS_ON
  - STRAIN-PHENOTYPE:PRESENTS
  - STRAIN-PROTEIN:PRODUCES
  - STRAIN-ORGANISM:INHABITS
  - STRAIN-COMPOUND:RESISTS
  - STRAIN-EFFECT:PROMOTES
  - STRAIN-ORGANISM:INFECTS
  - COMPOUND-STRAIN:INHIBITS
  - STRAIN-EFFECT:PRESENTS
  - STRAIN-DISEASE:ASSOCIATED_WITH
  - STRAIN-COMPOUND:DEGRADES
  - STRAIN-ORGANISM:SYMBIONT_OF
  - STRAIN-SPECIES:INHIBITS
  - STRAIN-ORGANISM:INHIBITS
  - STRAIN-EFFECT:INHIBITS
  - STRAIN-COMPOUND:PRODUCES
  - STRAIN-DISEASE:INHIBITS
model_sets:
  - train
  - dev
  - test
ner_epochs: 10
rel_epochs: 20
input_file: label/project-5-at-2024-04-29-09-34-8bf5e750.json
cutoff_prediction: 0.50
cuda_devices: [1,2,3]
# cuda_devices: [0]
ner_test: 0.35
rel_test: 0.35
# dataset: "1500"
dataset: "1000"
model: "large"
seed: 42
max_assemblies: 500
min_samples: 3
xgboost_device: 1
output_path: /home/gomez/gomez
# output_path: /home/tu/tu_tu/tu_bbpgo01/link
