ner_labels:
  - STRAIN
  - SPECIES
  - ISOLATE
  - COMPOUND
  - MEDIUM
  - ORGANISM
  - PHENOTYPE
  - EFFECT
  - DISEASE
rel_labels:
  - STRAIN-ISOLATE:INHABITS
  - STRAIN-MEDIUM:GROWS_ON
  - STRAIN-PHENOTYPE:PRESENTS
  - STRAIN-ORGANISM:INHABITS
  - STRAIN-COMPOUND:RESISTS
  - STRAIN-EFFECT:PROMOTES
  - STRAIN-ORGANISM:INFECTS
  - COMPOUND-STRAIN:INHIBITS
  - STRAIN-EFFECT:PRESENTS
  - STRAIN-DISEASE:ASSOCIATED_WITH
  - STRAIN-COMPOUND:DEGRADES
  - STRAIN-ORGANISM:SYMBIONT_OF
  - STRAIN-SPECIES:INHIBITS
  - STRAIN-ORGANISM:INHIBITS
  - STRAIN-EFFECT:INHIBITS
  - STRAIN-COMPOUND:PRODUCES
  - STRAIN-DISEASE:INHIBITS
model_sets:
  - train
  - dev
  - test
ner_epochs: 15
rel_epochs: 25
input_file: label/project-5-at-2024-12-30-15-29-f47f63e7.json
cutoff_prediction: 0.50
# cuda_devices: [1,2,3]
cuda_devices: [0]
ner_test: 0.25
rel_test: 0.4
dataset: "2812"
model: "large"
seed: 1
output_path: /home/tu/tu_tu/tu_kmpaj01/link
