ner_labels:
  - STRAIN
  - SPECIES
  - ISOLATE
  - COMPOUND
  - MEDIUM
  - ORGANISM
  - PHENOTYPE
  - DISEASE
rel_labels:
  - STRAIN-ISOLATE:INHABITS
  - STRAIN-MEDIUM:GROWS_ON
  - STRAIN-PHENOTYPE:PRESENTS
  - STRAIN-ORGANISM:INHABITS
  - STRAIN-COMPOUND:RESISTS
  - STRAIN-PHENOTYPE:PROMOTES
  - STRAIN-ORGANISM:INFECTS
  - COMPOUND-STRAIN:INHIBITS
  - STRAIN-DISEASE:ASSOCIATED_WITH
  - STRAIN-COMPOUND:DEGRADES
  - STRAIN-ORGANISM:SYMBIONT_OF
  - STRAIN-SPECIES:INHIBITS
  - STRAIN-ORGANISM:INHIBITS
  - STRAIN-PHENOTYPE:INHIBITS
  - STRAIN-COMPOUND:PRODUCES
  - STRAIN-DISEASE:INHIBITS
model_sets:
  - train
  - dev
  - test
ner_epochs: 15
rel_epochs: 25
input_file: label/project-10-at-2025-08-12-12-58-599fecc8.json
cutoff_prediction: 0.50
# cuda_devices: [1,2,3]
cuda_devices: [0]
ner_test: 0.2
rel_test: 0.3
dataset: 1108
model: "large"
seed: 97
output_path: /pfs/work9/workspace/scratch/tu_kmpaj01-link
pmc_parquet_file: snakemake_PMC/output/data/pmc_filtered.parquet
